// Image target data files generated by `npx @8thwall/image-target-cli@latest`.
//
// HOW TO ADD A NEW TARGET:
//   1. Run:  npx @8thwall/image-target-cli@latest
//      - A sharp, straight-on, well-lit photo of the object.
//      - Crop to the object only (answer "n" to the default crop); the crop is 3:4 or 4:3.
//      - Output folder: public/image-targets   (flat — the CLI writes imagePath as
//        "image-targets/<name>_luminance.jpg", so a subfolder breaks loading).
//   2. Import the JSON here and add it to IMAGE_TARGET_DATA below.
//   3. Set `imageTarget: '<name>'` on the matching entry in content/exhibits.js.

import catsPainting from '../../public/image-targets/cats-painting.json'

/** @type {Object[]} Image target descriptors as generated by image-target-cli. */

export const IMAGE_TARGET_DATA = [
  catsPainting,
]
