// Image target data files generated by `npx @8thwall/image-target-cli@latest`.
//
// HOW TO ADD A NEW TARGET:
//   1. Run:  npx @8thwall/image-target-cli@latest
//      - Point it at a clear, well-lit photo of the exhibit object.
//      - Name the target to match the exhibit code, e.g. "exhibit-01".
//   2. Copy the generated folder to public/image-targets/exhibit-01/
//   3. Import the JSON here and add it to IMAGE_TARGET_DATA below.
//   4. Set `imageTarget: 'exhibit-01'` on the matching entry in exhibits.js.
//
// Example (uncomment and repeat for each exhibit):
//   import exhibit01 from '../../public/image-targets/exhibit-01/exhibit-01.json'

export const IMAGE_TARGET_DATA = [
  // Paste generated imports here, one per exhibit.
]
